apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: testrungirl/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "1024Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always